# You might need for some reason to share access to the ec2 instnace but can't share your new pem file.
# The other user can have a pem file that you can add the private key from it to the ec2 instance by running this playbook. 
# Ask the other person to provide you with the output of the command 
# ssh-keygen -y -f /path_to_their_key-pair.pem
# another way to create it - ssh-keygen -t rsa -C "dba@example.org"

# Run the playbook like so

# ansible-playbook -i prep-env/new_hosts_{{ name }}.yml prep-env/step-by-step/touchauthorized_keys.yml 
# for example: 
# ansible-playbook -i prep-env/new_hosts_{{ name }}.yml prep-env/step-by-step/touchauthorized_keys.yml


- name: Add new key to nodes
  hosts: all
  gather_facts: False
  vars:
    user: dba
  tasks:
    - name: New Private Key
      lineinfile: 
        path: /home/{{ user }}/.ssh/authorized_keys 
        line: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        create: yes 
        state: present
