name: Build

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_VERSION: 2.14
    steps:
      - name: Echo my Date
        run: |
          echo "Invoke from main on $(date)"
          
      - name: Check last branch
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/confluentinc/cp-ansible/releases | jq -r '.[].tag_name' | sed 's/^v//' | sort | tail -n 1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            mosheblumberg/mosheblumbergansible:ansible${{ env.ANSIBLE_VERSION }}CP${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
