name: Maintenance

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: echo something
        run: echo "scheduled job"