name: Build Docker Container

on:
  push:
    branches:
      - build
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      VERSION: 7.6.1
      ANSIBLE_VERSION: 2.14
    steps:
      - name: Echo my Date
        run: |
          echo "Invoke from main on $(date)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            mosheblumberg/mosheblumbergansible:ansible${{ env.ANSIBLE_VERSION }}CP${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}