name: Debug Trigger

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Debugging script execution');
            const { owner, repo } = context.repo;
            console.log(`Owner: ${owner}, Repo: ${repo}`);
