name: Test Trigger

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test GitHub Script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('This is a test');
            const { owner, repo } = context.repo;
            console.log(`Owner: ${owner}, Repo: ${repo}`);
