name: Schedule Trigger

on:
  schedule:
    - cron: '5 3 * * *'  # At 03:05am every day
  workflow_dispatch:


jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Non-Default Branch Workflow via API
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PERSONAL_ACCESS_TOKEN" \
            https://api.github.com/repos/MosheBlumbergX/ansibleAsDocker/actions/workflows/build.yml/dispatches \
            -d '{"ref":"build"}'
