name: Schedule Trigger

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main  # Replace with your default branch name

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Non-Default Branch Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            console.log(`Owner: ${owner}, Repo: ${repo}`);
            try {
              const response = await github.rest.actions.createWorkflowDispatch({
                owner: owner,
                repo: repo,
                workflow_id: 'build.yml',  # Ensure this matches the workflow file name
                ref: 'build'  # Ensure this matches the target branch
              });
              console.log('Dispatch response:', response);
            } catch (error) {
              console.log('Error:', error);
            }
