name: Schedule Trigger

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main  # Replace with your default branch name

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Non-Default Branch Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: owner,
              repo: repo,
              workflow_id: 'maintenance.yml',
              ref: 'build'  # Replace 'build' with the actual branch name if different
            });
            console.log(response);
